= MuleSoft コネクタ認定プログラムのガイドラインについて
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: コネクタ, 認定, sdk, プログラムガイドライン

このドキュメントは、Mule 4 のコネクタ認定に関連します。Mule 3 の認定については、xref:3.9@connector-devkit::connector-certification-program-guidelines.adoc[DevKit ドキュメント]を参照してください。

MuleSoft のコネクタ認定プログラムでは、MuleSoft の認定を受けられる状態のエンタープライズグレードコネクタを作成するステップを順を追って説明します。認定されると、コネクタは Anypoint Exchange を介して顧客と開発者が検索および使用できるようになります。

== 開始する前に

認定プログラムに着手する前に、次の事項を検討し、これらの要件を順守できることを確認します。

* コネクタは最新かつ安全な状態に保ち、少なくとも年 1 回は再認定を受ける必要がある。
* コネクタは、エンタープライズバージョンの MuleSoft ソフトウェアまたは MuleSoft サービス用に作成および配布する必要がある。
* コネクタのすべてのトランザクションは、MuleSoft を介してではなく顧客とパートナー間で行われる必要がある。
* コネクタは完全に機能し、本番対応のエンタープライズグレードのアプリケーションおよびプロトコルコネクタである必要がある。つまり、Mule を外部システムと接続するコネクタである必要があります。
* コードは、継続的インテグレーション環境にデプロイできる状態になっている必要があります。コードは、非公開リポジトリをインポートすることなしにコマンドラインからコンパイルできる必要があります。ログイン情報は個別に提供され、コンパイル時に設定できる必要があります。さらに、認定にはコネクタの Sandbox ログイン情報が必要です。
* コネクタは、オープンソースまたは自分が所有するサードパーティライブラリのみを使用する必要がある。サードパーティの配布不可能なライブラリは使用できません。
* Anypoint Exchange に同様のコネクタがすでに存在する場合でも、既存のコネクタよりも優れた追加機能があれば、そのコネクタを送信可能。

== サポートの提供

パートナーまたは開発者は、Anypoint Exchange の各コネクタに対して完全なサポートを提供する必要があります。MuleSoft が受け取ったサポートの問い合わせについて、MuleSoft は商業的に合理的なレベルの Tier 1 の電話、Web ベースやメールによるサポートを顧客に直接提供します。MuleSoft は、市販の MuleSoft 製品に関連する問題を解決します。パートナーコネクタに固有の問題は、パートナーにエスカレートされます。

* パートナーは、1 営業日以内に MuleSoft からエスカレートされたすべてのサポート問い合わせに応答する。
* パートナーは、5 営業日以内に顧客の技術サポートの問題を解決するために最善を尽くす。

== コネクタの価格設定

パートナーまたは開発者は、コネクタを無料または有料で使用可能にするかどうかを決定する独自の裁量権を持ちます。ただし、Anypoint Studio 内ではすべてのコネクタを無料で使用できるようにする必要があります。必須ではありませんが、設計やデプロイメント用のコネクタのトライアルを顧客に提供することをお勧めします。

詳細は、下記の<<see_also,「カスタムモジュールライセンス」>>リンクを参照してください。

[%header,cols="20a,80a"]
|===
|カテゴリ |詳細
| 無料 |コネクタは、顧客が Anypoint Exchange を介してダウンロードして無料で使用できます。
| 有料 |有料コネクタは、Anypoint Studio での設計時に Mule アプリケーションで使用できます。デプロイメントでは、コネクタはライセンスがないと実行できません。顧客はパートナーから直接コネクタを購入する必要があり、MuleSoft が提供する生成されたライセンスキーを使用して、有料コネクタの使用を管理する必要があります。コネクタの価格設定は、パートナーによって決定されます。
|===

== ライセンス条件

`LICENSE.md` のライセンス規約の前に次の法的規約を追加します。
****
*MuleSoft 認定コネクタについて*

MuleSoft 認定コネクタは、MuleSoft のパートナーおよび開発者コミュニティによって開発されています。これらのコネクタは、MuleSoft によってレビューおよび認定されています。必要に応じて <コネクタ名> コネクタを購入したり、その支援やサポートを受けたりするには、直接  _<パートナー名>_  (_連絡先情報_) にお問い合わせください。MuleSoft は、MuleSoft 認定コネクタのサポートの一切の義務を放棄します。

コネクタをインストールすると、お客様は、MuleSoft がお客様の連絡先情報をこのコネクタの開発者と共有して、お客様がコネクタに関する詳細情報を開発者から直接受信できるようにすることに同意したことになります。

_独自のライセンス規約。_
****

== コンプライアンスのエクスポート

****
米国の法律で認められている場合を除き、MuleSoft から受け取った「MuleSoft の機密情報」や「MuleSoft ドキュメント」またはお客様の資料 (「パートナードキュメント」や「パートナーコネクタ」を含むがこれに限定されない) を使用することや、輸出または再輸出することはできません。特に、例外なく、「MuleSoft の機密情報」、「MuleSoft ドキュメント」およびお客様の資料は、次のいずれの者に対しても、輸出または再輸出を行うことができません。(a) 米国の通商禁止国 (b) 米国財務省の特別指定国リストまたは米国商務省の拒否人名リスト上の一切の者。
お客様は、上記国家に住居を定めていないこと、あるいは上記リストに該当するものではないことを表明および保証するものとします。また、お客様は、お客様が米国の法律で禁止されている目的で「MuleSoft の機密情報」や「MuleSoft ドキュメント」およびお客様の資料を使用または再輸出しないことに同意していただいたものとし、当該目的には核、化学兵器もしくは生物兵器の開発、設計、製造または生産を含みますがこれらに限定されません。

Anypoint Exchange を介したユーザへの資料の提供が、関連管轄区域における技術の輸出入に関するあらゆる規制に準拠していることを確認する責任は、お客様が単独で負うものとします。(大文字で表記された用語は、認定コネクタパートナー契約と同じ定義を持つものとします)。
****

== 開発および認定

開発するコネクタについて MuleSoft に通知し、mailto:isv@mulesoft.com[MuleSoft] に連絡して認定を受けます。MuleSoft から詳細情報についての連絡があります。

[[see_also]]
== 関連情報

* xref:certification-guidelines-for-connectors.adoc[コネクタ認証の技術ガイドライン]
* xref:license.adoc#custom-module-license[カスタムモジュールライセンス]
* https://forums.mulesoft.com[MuleSoft フォーラム]
* mailto:isv@mulesoft.com[MuleSoft へのお問い合わせ]